module.exports = {
  success: "Success",
  userNotFound: "User Not Found",
  loginSuccess: "User Login Success",
  loginFailed: "Invalid Email and Password",
  logoutSuccess: "User Logout Success",
  detailsUpdated: "profile details updated",
  dataUpdated: "Data Updated Successfully",
  dataFetched: "data fetched successfully",
  userDetailsRetrived: "User details retrieved",
  userBlocked: "User has been blocked",
  userStatusUpdated: "User status updated successfully",
  notificationStatusUpdated: "Notification Status Updated",
  noRecord: "No New User are not found",
  statusUpdated: "User unsubscribe status updated successfully",
  statusNotUpdated: "User blume status not updated",
  deletedData: "Data Deleted Successfully",
  addressDeleted: "Address Deleted Successfully",
  feedbackSumbitted: "Feedback submitted.",
  subadminCreated: "subadmin added successfully",
  subadminUpdated: "subadmin  updated successfully",
  subadminListed: "subadmin listed successfully",
  subadminData: "subadmin fetched successfully",
  subadminDelete: "subadmin deleted successfully",
  returnData: "Retun data fetched successfully",
  cancelData: "Cancel data fetched successfully",
  replacementData: "replacement data fetched successfully",
  unAuthorized: "Unauthorized request",
};
